//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnUcuzUrun.wsHepsiBurada {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsHepsiBurada.wsAddSoap")]
    public interface wsAddSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/urunFiyatiGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet urunFiyatiGetir(string urunKodu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/urunFiyatiGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> urunFiyatiGetirAsync(string urunKodu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAddSoapChannel : EnUcuzUrun.wsHepsiBurada.wsAddSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAddSoapClient : System.ServiceModel.ClientBase<EnUcuzUrun.wsHepsiBurada.wsAddSoap>, EnUcuzUrun.wsHepsiBurada.wsAddSoap {
        
        public wsAddSoapClient() {
        }
        
        public wsAddSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAddSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAddSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAddSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet urunFiyatiGetir(string urunKodu) {
            return base.Channel.urunFiyatiGetir(urunKodu);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> urunFiyatiGetirAsync(string urunKodu) {
            return base.Channel.urunFiyatiGetirAsync(urunKodu);
        }
    }
}
