//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowTemp.tempService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="tempService.wsAddSoap")]
    public interface wsAddSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTempValues", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTempValues();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTempValues", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTempValuesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAddSoapChannel : ShowTemp.tempService.wsAddSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAddSoapClient : System.ServiceModel.ClientBase<ShowTemp.tempService.wsAddSoap>, ShowTemp.tempService.wsAddSoap {
        
        public wsAddSoapClient() {
        }
        
        public wsAddSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAddSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAddSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAddSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetTempValues() {
            return base.Channel.GetTempValues();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTempValuesAsync() {
            return base.Channel.GetTempValuesAsync();
        }
    }
}
